#h2database

#Dados de conexão com o banco H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    passaword:

   #Configuração do cliente web do banco H2
    h2:
      consoble:
        enabled: true
        path: /h2-console

      #Configuração pra mostrar o SQL no console
      jpa:
      show-sql: true
      properties:
        hibernate:
          formate_sql: true

